trigger:
- main

pool:
  name: Mac-Ubuntu2204

variables:
  includeInstallSteps: false  # Set this to true to include installation steps

stages:
- stage: PrepareAgent
  jobs:
  - job: PrepareAgentMachine
    steps:
    - ${{ if eq(variables.includeInstallSteps, 'true') }}:
      - template: templates/install_dependencies.yml

    - task: Bash@3
      displayName: 'List contents of source directory'
      inputs:
        targetType: 'inline'
        script: |
          ls -la $(Build.SourcesDirectory)

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: Bash@3
      displayName: 'List contents of artifact staging directory'
      inputs:
        targetType: 'inline'
        script: |
          ls -la $(Build.ArtifactStagingDirectory)

- stage: PrepareVMware
  jobs:
  - job: PrepareVMwareEnvironment
    steps:
    - task: Bash@3
      displayName: 'Run Prepare VMware Playbook'
      inputs:
        targetType: 'inline'
        script: |
          cd $(Build.ArtifactStagingDirectory)
          ansible-playbook -i inventory/hosts site.yml --tags prepare_vmware

- stage: DeployONTAPSelect
  jobs:
  - job: DeployONTAPSelect
    steps:
    - task: Bash@3
      displayName: 'Run Deploy ONTAP Select Playbook'
      inputs:
        targetType: 'inline'
        script: |
          cd $(Build.ArtifactStagingDirectory)
          ansible-playbook -i inventory/hosts site.yml --tags deploy_ontap_select

- stage: CreateONTAPCluster
  jobs:
  - job: CreateONTAPCluster
    steps:
    - task: Bash@3
      displayName: 'Run Create ONTAP Cluster Playbook'
      inputs:
        targetType: 'inline'
        script: |
          cd $(Build.ArtifactStagingDirectory)
          ansible-playbook -i inventory/hosts site.yml --tags create_ontap_cluster
