---
- name: Prepare VMware Environment
  hosts: localhost
  roles:
    - prepare_vmware
  tags: prepare_vmware

- name: Deploy ONTAP Select
  hosts: localhost
  roles:
    - deploy_ontap_select

- name: Deploy Cluster
  hosts: localhost
  roles:
    - deploy_cluster
