# main.yml

---
- name: Prepare VMware environment
  hosts: vmware_hosts
  roles:
    - prepare_vmware_environment

- name: Deploy ONTAP Select
  hosts: ontap_nodes
  roles:
    - deploy_ontap_select
