---
- name: Prepare VMware Environment
  hosts: localhost
  roles:
    - role: prepare_vmware
      tags: prepare_vmware

- name: Deploy ONTAP Select
  hosts: localhost
  roles:
    - role: ontap_select_deploy
      tags: deploy_ontap_select

- name: Create ONTAP Cluster
  hosts: localhost
  roles:
    - role: ontap_cluster_create
      tags: create_ontap_cluster
