---
- name: Prepare VMware Environment
  hosts: localhost
  roles:
    - prepare_vmware

- name: Deploy ONTAP Select
  hosts: all_vm_nodes
  roles:
    - ontap_select_deploy

- name: Deploy ONTAP Cluster
  hosts: localhost
  roles:
    - ontap_cluster
  vars:
    cluster_size: "{{ cluster_size }}"
